// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcxjggnignrchfgrjnpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeGpnZ25pZ25yY2hmZ3JqbnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxOTE4MzAsImV4cCI6MjA2OTc2NzgzMH0.3T2eBju9aj9_dOdXIsjD8_88J96EJ6HJVlqWEvl2GbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});